apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-empty-private-knnf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-dockerfile-empty-private-knnf
    app.kubernetes.io/part-of: mc-golang-without
  name: devfile-sample-go-basic-dockerfile-empty-private-knnf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-empty-private-knnf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-dockerfile-empty-private-knnf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qqqe-tenant/mc-golang-without/devfile-sample-go-basic-dockerfile-empty-private-knnf@sha256:c0148d1900482aa5e8f40fb0bab18ca669a17059b200095ffeaaa0aa3a65fa13
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
