apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-dockerfile-empty-private-knnf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qqqe-tenant/mc-golang-without/devfile-sample-go-basic-dockerfile-empty-private-knnf@sha256:c0148d1900482aa5e8f40fb0bab18ca669a17059b200095ffeaaa0aa3a65fa13
        name: my-go
        resources: {}
status: {}
